name: Unit Tests
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: xvfb-run --auto-servernum mvn test -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}